version: '3'

services:
  django:
    build: ./todo_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./todo_backend:/code

  fastapi:
    build: ./fast_api
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - django

  redis:
    image: redis
    ports:
      - "6379:6379"

  telegram_bot:
    build: ./telegram_bot
    command: python bot.py
    depends_on:
      - django
      - fastapi

  celery:
    build: ./todo_backend
    command: celery -A todo_backend worker --loglevel=info
    depends_on:
      - django
      - redis

  celery_beat:
    build: ./todo_backend
    command: celery -A todo_backend beat --loglevel=info
    depends_on:
      - django
      - redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
